# Generated by Django 5.2.5 on 2025-08-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0002_schedulestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fitness_goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('hypertrophy', 'Hypertrophy (Muscle Gain)'), ('endurance', 'Endurance'), ('rehab', 'Rehab'), ('sport_specific', 'Sport Specific')], max_length=50, null=True)),
                ('fitness_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True)),
                ('days_per_week', models.IntegerField(blank=True, null=True)),
                ('equipment_access', models.CharField(blank=True, choices=[('none', 'None'), ('home_gym', 'Home Gym (dumbbells, bands)'), ('full_gym', 'Full Gym Access')], max_length=50, null=True)),
            ],
        ),
    ]
