# Generated by Django 5.0.7 on 2024-08-15 05:00

from django.db import migrations

def populate_exercises(apps, schema_editor):
    Exercise = apps.get_model('tracker', 'Exercise')
    
    exercises = [
        # Chest
        {'name': 'Bench Press', 'muscle_group': 'chest', 'equipment': 'barbell', 'difficulty': 'intermediate'},
        {'name': 'Dumbbell Bench Press', 'muscle_group': 'chest', 'equipment': 'dumbbell', 'difficulty': 'intermediate'},
        {'name': 'Incline Bench Press', 'muscle_group': 'chest', 'equipment': 'barbell', 'difficulty': 'intermediate'},
        {'name': 'Push-up', 'muscle_group': 'chest', 'equipment': 'bodyweight', 'difficulty': 'beginner'},
        {'name': 'Chest Fly', 'muscle_group': 'chest', 'equipment': 'dumbbell', 'difficulty': 'beginner'},
        {'name': 'Machine Chest Press', 'muscle_group': 'chest', 'equipment': 'machine', 'difficulty': 'beginner'},
        
        # Back
        {'name': 'Pull-up', 'muscle_group': 'back', 'equipment': 'bodyweight', 'difficulty': 'advanced'},
        {'name': 'Deadlift', 'muscle_group': 'back', 'equipment': 'barbell', 'difficulty': 'advanced'},
        {'name': 'Bent-over Row', 'muscle_group': 'back', 'equipment': 'barbell', 'difficulty': 'intermediate'},
        {'name': 'Lat Pulldown', 'muscle_group': 'back', 'equipment': 'machine', 'difficulty': 'beginner'},
        {'name': 'Seated Cable Row', 'muscle_group': 'back', 'equipment': 'machine', 'difficulty': 'beginner'},
        {'name': 'Dumbbell Row', 'muscle_group': 'back', 'equipment': 'dumbbell', 'difficulty': 'beginner'},
        
        # Legs
        {'name': 'Squat', 'muscle_group': 'legs', 'equipment': 'barbell', 'difficulty': 'intermediate'},
        {'name': 'Leg Press', 'muscle_group': 'legs', 'equipment': 'machine', 'difficulty': 'beginner'},
        {'name': 'Lunge', 'muscle_group': 'legs', 'equipment': 'dumbbell', 'difficulty': 'beginner'},
        {'name': 'Leg Extension', 'muscle_group': 'legs', 'equipment': 'machine', 'difficulty': 'beginner'},
        {'name': 'Leg Curl', 'muscle_group': 'legs', 'equipment': 'machine', 'difficulty': 'beginner'},
        {'name': 'Calf Raise', 'muscle_group': 'legs', 'equipment': 'dumbbell', 'difficulty': 'beginner'},

        # Shoulders
        {'name': 'Overhead Press', 'muscle_group': 'shoulders', 'equipment': 'barbell', 'difficulty': 'intermediate'},
        {'name': 'Dumbbell Shoulder Press', 'muscle_group': 'shoulders', 'equipment': 'dumbbell', 'difficulty': 'intermediate'},
        {'name': 'Lateral Raise', 'muscle_group': 'shoulders', 'equipment': 'dumbbell', 'difficulty': 'beginner'},
        {'name': 'Front Raise', 'muscle_group': 'shoulders', 'equipment': 'dumbbell', 'difficulty': 'beginner'},
        
        # Biceps
        {'name': 'Barbell Curl', 'muscle_group': 'biceps', 'equipment': 'barbell', 'difficulty': 'beginner'},
        {'name': 'Dumbbell Curl', 'muscle_group': 'biceps', 'equipment': 'dumbbell', 'difficulty': 'beginner'},
        {'name': 'Hammer Curl', 'muscle_group': 'biceps', 'equipment': 'dumbbell', 'difficulty': 'beginner'},

        # Triceps
        {'name': 'Tricep Pushdown', 'muscle_group': 'triceps', 'equipment': 'machine', 'difficulty': 'beginner'},
        {'name': 'Overhead Tricep Extension', 'muscle_group': 'triceps', 'equipment': 'dumbbell', 'difficulty': 'beginner'},
        {'name': 'Close-grip Bench Press', 'muscle_group': 'triceps', 'equipment': 'barbell', 'difficulty': 'intermediate'},
        
        # Core
        {'name': 'Plank', 'muscle_group': 'core', 'equipment': 'bodyweight', 'difficulty': 'beginner'},
        {'name': 'Crunch', 'muscle_group': 'core', 'equipment': 'bodyweight', 'difficulty': 'beginner'},
        {'name': 'Leg Raise', 'muscle_group': 'core', 'equipment': 'bodyweight', 'difficulty': 'intermediate'},
        {'name': 'Russian Twist', 'muscle_group': 'core', 'equipment': 'dumbbell', 'difficulty': 'intermediate'},

        # Cardio
        {'name': 'Treadmill Running', 'muscle_group': 'cardio', 'equipment': 'cardio_machine', 'difficulty': 'beginner'},
        {'name': 'Cycling', 'muscle_group': 'cardio', 'equipment': 'cardio_machine', 'difficulty': 'beginner'},
        {'name': 'Rowing', 'muscle_group': 'cardio', 'equipment': 'cardio_machine', 'difficulty': 'intermediate'},
    ]

    for exercise_data in exercises:
        Exercise.objects.create(**exercise_data)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_exercise'),
    ]

    operations = [
        migrations.RunPython(populate_exercises),
    ]
