# Generated by Django 5.2.5 on 2025-08-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_exercise'),
    ]

    operations = [
    ]
