# Generated by Django 5.2.5 on 2025-08-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_bodymeasurement_cardioentry_exercisecatalog_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('calories_per_100g', models.FloatField()),
                ('protein_g_per_100g', models.FloatField(default=0.0)),
                ('carbs_g_per_100g', models.FloatField(default=0.0)),
                ('fat_g_per_100g', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='quantity_grams',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
