# Generated by Django 5.2.5 on 2025-08-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_foodcatalog_nutritionlog_quantity_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecatalog',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercisecatalog',
            name='equipment_needed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercisecatalog',
            name='recommended_for_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('performance', 'Performance'), ('general_fitness', 'General Fitness')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercisecatalog',
            name='target_muscle_groups',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
