# Generated by Django 5.2.5 on 2025-08-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_exercisecatalog_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('group', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exercisecatalog',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='tracker.equipment'),
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercisecatalog')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.muscle')),
            ],
            options={
                'unique_together': {('exercise', 'muscle', 'role')},
            },
        ),
        migrations.AddField(
            model_name='exercisecatalog',
            name='muscles',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='tracker.ExerciseMuscle', to='tracker.muscle'),
        ),
        migrations.AddField(
            model_name='exercisecatalog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='tracker.tag'),
        ),
    ]
