# Generated by Django 5.2.5 on 2025-08-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_equipment_muscle_tag_exercisecatalog_equipments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='chest_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='hips_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='l_bicep_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='l_calf_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='l_forearm_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='l_thigh_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='neck_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='r_bicep_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='r_calf_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='r_forearm_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='r_thigh_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='shoulder_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='skinfold_sum_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='waist_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.exercisecatalog'),
        ),
        migrations.AddField(
            model_name='goal',
            name='metric',
            field=models.CharField(choices=[('weight_kg', 'Body Weight (kg)'), ('body_fat', 'Body Fat (%)'), ('lift_kg', 'Lift (kg)')], default='weight_kg', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
