# Generated by Django 5.2.5 on 2025-09-09 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_calculatorresult_macrotarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('achievement_type', models.CharField(choices=[('workout_count', 'Workout Count'), ('streak', 'Streak'), ('weight_loss', 'Weight Loss'), ('strength_gain', 'Strength Gain'), ('consistency', 'Consistency'), ('social', 'Social'), ('challenge', 'Challenge')], max_length=30)),
                ('required_value', models.FloatField()),
                ('required_unit', models.CharField(default='', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('points_value', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rarity', 'points_value'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metric_type', models.CharField(choices=[('total_volume', 'Total Volume'), ('workout_streak', 'Workout Streak'), ('weight_lost', 'Weight Lost'), ('strength_gained', 'Strength Gained'), ('consistency', 'Consistency'), ('challenge_wins', 'Challenge Wins')], max_length=30)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all_time', 'All Time')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('auto_update', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('workout_frequency', 'Workout Frequency'), ('weight_loss', 'Weight Loss'), ('strength_gain', 'Strength Gain'), ('distance', 'Distance'), ('duration', 'Duration'), ('custom', 'Custom')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_value', models.FloatField()),
                ('target_unit', models.CharField(max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('reps', models.IntegerField()),
                ('date_achieved', models.DateField()),
                ('record_type', models.CharField(choices=[('max_weight', 'Max Weight'), ('max_reps', 'Max Reps'), ('max_volume', 'Max Volume'), ('one_rm', 'One Rep Max')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercisecatalog')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.workoutsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('current_progress', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tracker.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-final_score', 'joined_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('score', models.FloatField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.leaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-score'],
                'unique_together': {('leaderboard', 'user', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='ProgressAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_volume_kg', models.FloatField(default=0)),
                ('total_sets', models.IntegerField(default=0)),
                ('total_reps', models.IntegerField(default=0)),
                ('unique_exercises', models.IntegerField(default=0)),
                ('total_cardio_minutes', models.IntegerField(default=0)),
                ('total_distance_km', models.FloatField(default=0)),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein_g', models.FloatField(default=0)),
                ('total_carbs_g', models.FloatField(default=0)),
                ('total_fat_g', models.FloatField(default=0)),
                ('macro_balance_score', models.FloatField(default=0)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('recovery_score', models.FloatField(default=0)),
                ('workout_intensity', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress_value', models.FloatField(default=0)),
                ('is_displayed', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tracker.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection_type', models.CharField(choices=[('friend', 'Friend'), ('follower', 'Follower'), ('trainer', 'Trainer'), ('trainee', 'Trainee')], default='friend', max_length=20)),
                ('can_view_workouts', models.BooleanField(default=True)),
                ('can_view_progress', models.BooleanField(default=True)),
                ('can_view_nutrition', models.BooleanField(default=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('workouts_this_week', models.IntegerField(default=0)),
                ('target_weekly_workouts', models.IntegerField(default=3)),
                ('workouts_this_month', models.IntegerField(default=0)),
                ('total_workouts', models.IntegerField(default=0)),
                ('consistency_percentage', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
