# Generated by Django 5.2.5 on 2025-09-09 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_achievement_leaderboard_challenge_personalrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_system', models.CharField(choices=[('imperial', 'Imperial (lb/mi)'), ('metric', 'Metric (kg/km)')], default='imperial', max_length=16)),
                ('distance_unit', models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], default='mi', max_length=2)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('primary_goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('performance', 'Performance'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=32)),
                ('available_equipment', models.TextField(blank=True, null=True)),
                ('preferred_workout_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('midday', 'Midday'), ('evening', 'Evening')], max_length=16, null=True)),
                ('workout_frequency', models.IntegerField(blank=True, null=True)),
                ('fitness_level', models.CharField(blank=True, default='beginner', max_length=24)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
