# Generated by Django 5.2.5 on 2025-09-10 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('front', 'Front View'), ('side', 'Side View'), ('back', 'Back View'), ('flexed', 'Flexed'), ('relaxed', 'Relaxed'), ('before', 'Before Photo'), ('after', 'After Photo'), ('milestone', 'Milestone Photo')], max_length=20)),
                ('image', models.ImageField(upload_to='progress_photos/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='progress_thumbnails/%Y/%m/%d/')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('weight_at_time', models.FloatField(blank=True, help_text='Weight when photo was taken', null=True)),
                ('body_fat_at_time', models.FloatField(blank=True, help_text='Body fat % when photo was taken', null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this photo')),
                ('is_analyzed', models.BooleanField(default=False)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('allow_comparisons', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Photo',
                'verbose_name_plural': 'Progress Photos',
                'ordering': ['-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='ProgressMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength_gain', 'Strength Gain'), ('endurance', 'Endurance'), ('consistency', 'Consistency'), ('transformation', 'Transformation')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('achieved_value', models.FloatField(blank=True, null=True)),
                ('achievement_date', models.DateTimeField(auto_now_add=True)),
                ('is_celebrated', models.BooleanField(default=False)),
                ('celebration_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_milestones', to=settings.AUTH_USER_MODEL)),
                ('milestone_photos', models.ManyToManyField(blank=True, to='tracker.progressphoto')),
            ],
            options={
                'verbose_name': 'Progress Milestone',
                'verbose_name_plural': 'Progress Milestones',
                'ordering': ['-achievement_date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_type', models.CharField(choices=[('before_after', 'Before/After'), ('progress', 'Progress Timeline'), ('milestone', 'Milestone Comparison')], max_length=20)),
                ('time_difference_days', models.IntegerField(blank=True, null=True)),
                ('weight_change', models.FloatField(blank=True, null=True)),
                ('body_fat_change', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comparisons', to=settings.AUTH_USER_MODEL)),
                ('after_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_comparisons', to='tracker.progressphoto')),
                ('before_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_comparisons', to='tracker.progressphoto')),
            ],
            options={
                'verbose_name': 'Photo Comparison',
                'verbose_name_plural': 'Photo Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyPartMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('neck', 'Neck'), ('chest', 'Chest'), ('shoulders', 'Shoulders'), ('left_bicep', 'Left Bicep'), ('right_bicep', 'Right Bicep'), ('left_forearm', 'Left Forearm'), ('right_forearm', 'Right Forearm'), ('waist', 'Waist'), ('hips', 'Hips'), ('left_thigh', 'Left Thigh'), ('right_thigh', 'Right Thigh'), ('left_calf', 'Left Calf'), ('right_calf', 'Right Calf')], max_length=20)),
                ('measurement_cm', models.FloatField()),
                ('measurement_inches', models.FloatField(blank=True, null=True)),
                ('is_flexed', models.BooleanField(default=False)),
                ('is_relaxed', models.BooleanField(default=True)),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_part_measurements', to=settings.AUTH_USER_MODEL)),
                ('progress_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.progressphoto')),
            ],
            options={
                'verbose_name': 'Body Part Measurement',
                'verbose_name_plural': 'Body Part Measurements',
                'ordering': ['-measurement_date'],
            },
        ),
    ]
