# Generated by Django 5.2.5 on 2025-09-10 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_progressphoto_progressmilestone_photocomparison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('core', 'Core'), ('quads', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('neck', 'Neck')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Muscle Group',
                'verbose_name_plural': 'Muscle Groups',
            },
        ),
        migrations.CreateModel(
            name='BodyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight_kg', models.FloatField()),
                ('body_fat_percentage', models.FloatField()),
                ('muscle_mass_kg', models.FloatField()),
                ('bone_mass_kg', models.FloatField(blank=True, null=True)),
                ('water_percentage', models.FloatField(blank=True, null=True)),
                ('visceral_fat_level', models.IntegerField(blank=True, null=True)),
                ('bmr_calories', models.IntegerField(blank=True, null=True)),
                ('metabolic_age', models.IntegerField(blank=True, null=True)),
                ('body_shape_type', models.CharField(blank=True, choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph'), ('balanced', 'Balanced')], max_length=20, null=True)),
                ('measurement_method', models.CharField(choices=[('scale', 'Smart Scale'), ('calipers', 'Skinfold Calipers'), ('dexa', 'DEXA Scan'), ('bodpod', 'BodPod'), ('manual', 'Manual Calculation')], default='scale', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_compositions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Body Composition',
                'verbose_name_plural': 'Body Compositions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BodyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('total_muscle_growth_kg', models.FloatField(default=0)),
                ('total_fat_loss_kg', models.FloatField(default=0)),
                ('net_weight_change_kg', models.FloatField(default=0)),
                ('body_fat_trend', models.CharField(choices=[('decreasing', 'Decreasing'), ('stable', 'Stable'), ('increasing', 'Increasing'), ('fluctuating', 'Fluctuating')], max_length=20)),
                ('muscle_mass_trend', models.CharField(choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing'), ('fluctuating', 'Fluctuating')], max_length=20)),
                ('symmetry_score', models.FloatField(blank=True, null=True)),
                ('balance_score', models.FloatField(blank=True, null=True)),
                ('progress_score', models.FloatField(blank=True, null=True)),
                ('predicted_body_fat_30_days', models.FloatField(blank=True, null=True)),
                ('predicted_muscle_mass_30_days', models.FloatField(blank=True, null=True)),
                ('predicted_weight_30_days', models.FloatField(blank=True, null=True)),
                ('key_insights', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_analytics', to=settings.AUTH_USER_MODEL)),
                ('fastest_growing_muscle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastest_growing', to='tracker.musclegroup')),
                ('slowest_growing_muscle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slowest_growing', to='tracker.musclegroup')),
            ],
            options={
                'verbose_name': 'Body Analytics',
                'verbose_name_plural': 'Body Analytics',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroupMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('circumference_cm', models.FloatField()),
                ('circumference_inches', models.FloatField(blank=True, null=True)),
                ('muscle_density', models.CharField(blank=True, choices=[('soft', 'Soft'), ('firm', 'Firm'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], max_length=20, null=True)),
                ('is_flexed', models.BooleanField(default=False)),
                ('is_pumped', models.BooleanField(default=False)),
                ('workout_context', models.CharField(choices=[('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout'), ('rest_day', 'Rest Day'), ('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('body_composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.bodycomposition')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.musclegroup')),
                ('progress_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.progressphoto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Muscle Group Measurement',
                'verbose_name_plural': 'Muscle Group Measurements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('prediction_horizon_days', models.IntegerField(default=30)),
                ('confidence_level', models.FloatField(default=0.85)),
                ('predicted_weight', models.FloatField()),
                ('predicted_body_fat', models.FloatField()),
                ('predicted_muscle_mass', models.FloatField()),
                ('muscle_predictions', models.JSONField(blank=True, default=dict)),
                ('current_trends', models.JSONField(blank=True, default=dict)),
                ('historical_data_points', models.IntegerField(default=0)),
                ('prediction_accuracy_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('actual_vs_predicted', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Prediction',
                'verbose_name_plural': 'Progress Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
    ]
