# Generated by Django 5.2.5 on 2025-09-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_musclegroup_bodycomposition_bodyanalytics_and_more'),
    ]

    operations = [
    ]
