# Generated by Django 5.2.5 on 2025-09-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20250920_1205'),
    ]

    operations = [
    ]
