# Generated by Django 5.2.5 on 2025-09-25 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_foodcategory_alter_exercisecatalog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_keyword', models.CharField(max_length=100)),
                ('rule', models.CharField(choices=[('avoid', 'Avoid'), ('modify', 'Modify'), ('limit', 'Limit')], default='avoid', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.exercisecatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_contras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(default='PPL', max_length=20)),
                ('days_per_week', models.IntegerField(default=4)),
                ('session_duration', models.IntegerField(default=60)),
                ('level', models.CharField(default='intermediate', max_length=20)),
                ('primary_goal', models.CharField(default='general_fitness', max_length=32)),
                ('intensity_model', models.CharField(default='standard', max_length=20)),
                ('rest_between_sets_sec', models.IntegerField(default=90)),
                ('equipment', models.TextField(blank=True, default='Barbell,Dumbbells,Bench')),
                ('emphasis', models.CharField(blank=True, default='balanced', max_length=50)),
                ('kcal_strategy', models.CharField(default='maintain', max_length=20)),
                ('macros', models.CharField(default='40/30/30', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
