# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_exercisecontraindication_trainerprofile'),
    ]

    operations = [
        # Raw time-series tables for high-frequency data (SQLite compatible)
        migrations.RunSQL(
            """
            -- Raw HR samples (1Hz from devices)
            CREATE TABLE IF NOT EXISTS tracker_hr_sample (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                session_id INTEGER,
                timestamp DATETIME NOT NULL,
                heart_rate INTEGER NOT NULL CHECK (heart_rate >= 30 AND heart_rate <= 220),
                device_id VARCHAR(50),
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            -- Raw GPS points (for outdoor cardio)
            CREATE TABLE IF NOT EXISTS tracker_gps_point (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                session_id INTEGER,
                timestamp DATETIME NOT NULL,
                latitude DECIMAL(10, 8) NOT NULL,
                longitude DECIMAL(11, 8) NOT NULL,
                altitude DECIMAL(8, 2),
                speed DECIMAL(6, 2),
                accuracy DECIMAL(6, 2),
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            -- Indexes for time-series queries
            CREATE INDEX IF NOT EXISTS idx_hr_sample_user_timestamp 
                ON tracker_hr_sample (user_id, timestamp DESC);
            CREATE INDEX IF NOT EXISTS idx_hr_sample_session 
                ON tracker_hr_sample (session_id, timestamp);
            CREATE INDEX IF NOT EXISTS idx_gps_point_user_timestamp 
                ON tracker_gps_point (user_id, timestamp DESC);
            CREATE INDEX IF NOT EXISTS idx_gps_point_session 
                ON tracker_gps_point (session_id, timestamp);

            -- Daily aggregates tables (SQLite equivalent of materialized views)
            CREATE TABLE IF NOT EXISTS tracker_cardio_load_daily (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                date DATE NOT NULL,
                total_samples INTEGER DEFAULT 0,
                avg_hr REAL DEFAULT 0,
                max_hr INTEGER DEFAULT 0,
                min_hr INTEGER DEFAULT 0,
                total_trimp INTEGER DEFAULT 0,
                sessions_count INTEGER DEFAULT 0,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(user_id, date)
            );

            CREATE TABLE IF NOT EXISTS tracker_strength_summary_daily (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                date DATE NOT NULL,
                sessions_count INTEGER DEFAULT 0,
                exercises_count INTEGER DEFAULT 0,
                total_tonnage REAL DEFAULT 0,
                avg_tonnage_per_session REAL DEFAULT 0,
                max_weight_lifted REAL DEFAULT 0,
                best_e1rm REAL DEFAULT 0,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(user_id, date)
            );

            CREATE TABLE IF NOT EXISTS tracker_weight_trend_daily (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                date DATE NOT NULL,
                current_weight REAL,
                previous_weight REAL,
                weight_change REAL,
                body_fat_percentage REAL,
                muscle_mass REAL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(user_id, date)
            );

            -- Indexes for daily aggregates
            CREATE INDEX IF NOT EXISTS idx_cardio_load_daily_user_date 
                ON tracker_cardio_load_daily (user_id, date);
            CREATE INDEX IF NOT EXISTS idx_strength_summary_daily_user_date 
                ON tracker_strength_summary_daily (user_id, date);
            CREATE INDEX IF NOT EXISTS idx_weight_trend_daily_user_date 
                ON tracker_weight_trend_daily (user_id, date);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS tracker_weight_trend_daily;
            DROP TABLE IF EXISTS tracker_strength_summary_daily;
            DROP TABLE IF EXISTS tracker_cardio_load_daily;
            DROP TABLE IF EXISTS tracker_gps_point;
            DROP TABLE IF EXISTS tracker_hr_sample;
            """
        ),
    ]
