# Generated by Django 5.2.5

from django.db import migrations


def create_minute_buckets(apps, schema_editor):
    """Create live minute buckets table for real-time aggregation"""
    if schema_editor.connection.vendor == 'sqlite':
        # SQLite version - execute statements one at a time
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS tracker_minute_hr (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                minute_ts DATETIME NOT NULL,
                avg_bpm INTEGER NOT NULL,
                samples INTEGER NOT NULL DEFAULT 1,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(user_id, minute_ts)
            )
        """)
        
        schema_editor.execute("""
            CREATE INDEX IF NOT EXISTS idx_minute_hr_user_minute 
                ON tracker_minute_hr (user_id, minute_ts)
        """)
        
        schema_editor.execute("""
            CREATE INDEX IF NOT EXISTS idx_minute_hr_day 
                ON tracker_minute_hr (user_id, DATE(minute_ts))
        """)
    else:
        # PostgreSQL version
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS tracker_minute_hr (
                id BIGSERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL,
                minute_ts TIMESTAMPTZ NOT NULL,
                avg_bpm INTEGER NOT NULL,
                samples INTEGER NOT NULL DEFAULT 1,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW(),
                UNIQUE(user_id, minute_ts)
            )
        """)
        
        schema_editor.execute("""
            CREATE INDEX IF NOT EXISTS idx_minute_hr_user_minute 
                ON tracker_minute_hr (user_id, minute_ts)
        """)
        
        schema_editor.execute("""
            CREATE INDEX IF NOT EXISTS idx_minute_hr_day 
                ON tracker_minute_hr (user_id, date_trunc('day', minute_ts))
        """)


def drop_minute_buckets(apps, schema_editor):
    """Drop live minute buckets table"""
    schema_editor.execute("DROP TABLE IF EXISTS tracker_minute_hr;")


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_timeseries_and_aggregates'),
    ]

    operations = [
        migrations.RunPython(create_minute_buckets, drop_minute_buckets),
    ]
