# Generated by Django 5.2.5 on 2025-10-03 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_activity_activitycomment_activitylike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('consistency', 'Consistency'), ('social', 'Social'), ('nutrition', 'Nutrition'), ('special', 'Special'), ('milestone', 'Milestone')], max_length=30)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('xp_required', models.IntegerField(default=0)),
                ('level_required', models.IntegerField(default=0)),
                ('streak_required', models.IntegerField(default=0)),
                ('workouts_required', models.IntegerField(default=0)),
                ('challenges_required', models.IntegerField(default=0)),
                ('special_requirements', models.JSONField(blank=True, default=dict)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'rarity', 'xp_required'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(choices=[('workout', 'Complete Workout'), ('social', 'Social Interaction'), ('challenge', 'Challenge Activity'), ('streak', 'Maintain Streak'), ('nutrition', 'Nutrition Goal'), ('custom', 'Custom Quest')], max_length=30)),
                ('requirements', models.JSONField(default=dict)),
                ('xp_reward', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.badge')),
            ],
            options={
                'ordering': ['difficulty', 'xp_reward'],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('xp_to_next_level', models.IntegerField(default=1000)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_achievements', models.IntegerField(default=0)),
                ('total_workouts', models.IntegerField(default=0)),
                ('total_challenges_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='StreakBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_days', models.IntegerField(unique=True)),
                ('xp_multiplier', models.FloatField(default=1.0)),
                ('bonus_xp', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.badge')),
            ],
            options={
                'ordering': ['streak_days'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('earned_data', models.JSONField(blank=True, default=dict)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tracker.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserDailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_claimed', models.BooleanField(default=False)),
                ('badge_claimed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tracker.dailyquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'quest__difficulty'],
                'unique_together': {('user', 'quest', 'date')},
            },
        ),
    ]
