# Generated by Cursor AI for Maverick Aim Rush
from django.contrib import admin
from .models import (
    Goal, BodyMeasurement, ExerciseCatalog, WorkoutSession, StrengthSet,
    CardioEntry, NutritionLog, SleepLog, InjuryLog, Plan, PlannedExercise,
    MacroTarget, CalculatorResult, ProgressAnalytics, PersonalRecord,
    WorkoutStreak, UserConnection, Challenge, ChallengeParticipation,
    Leaderboard, LeaderboardEntry, Achievement, UserAchievement
)

# Register models for quick admin entry
admin.site.register(Goal)
admin.site.register(BodyMeasurement)
admin.site.register(ExerciseCatalog)
admin.site.register(WorkoutSession)
admin.site.register(StrengthSet)
admin.site.register(CardioEntry)
admin.site.register(NutritionLog)
admin.site.register(SleepLog)
admin.site.register(InjuryLog)
admin.site.register(Plan)
admin.site.register(PlannedExercise)
admin.site.register(MacroTarget)
admin.site.register(CalculatorResult)
admin.site.register(ProgressAnalytics)
admin.site.register(PersonalRecord)
admin.site.register(WorkoutStreak)
admin.site.register(UserConnection)
admin.site.register(Challenge)
admin.site.register(ChallengeParticipation)
admin.site.register(Leaderboard)
admin.site.register(LeaderboardEntry)
admin.site.register(Achievement)
admin.site.register(UserAchievement)
