# Generated by Cursor AI for Maverick Aim Rush
# WebSocket routing configuration

from django.urls import re_path
from . import consumers

websocket_urlpatterns = [
    re_path(r'ws/workout/(?P<session_id>\w+)/$', consumers.WorkoutConsumer.as_asgi()),
    re_path(r'ws/dashboard/(?P<user_id>\w+)/$', consumers.DashboardConsumer.as_asgi()),
    re_path(r'ws/social/$', consumers.SocialConsumer.as_asgi()),
    re_path(r'ws/test/$', consumers.TestConsumer.as_asgi()),  # Add test consumer
    re_path(r'ws/simple-test/$', consumers.SimpleTestConsumer.as_asgi()),  # Simple test without auth
]
