# Generated by Cursor AI for Maverick Aim Rush
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    RegisterView, NutritionLogViewSet, FoodCatalogViewSet, WorkoutSessionViewSet,
    StrengthSetViewSet, CardioEntryViewSet, ExerciseCatalogViewSet,
    MuscleViewSet, EquipmentViewSet, TagViewSet, WeeklyPlanView, ProgressStatsView, ProgressExerciseTrendView, MeasurementViewSet, GoalViewSet
)

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'exercises', ExerciseCatalogViewSet, basename='exercisecatalog')
router.register(r'foods', FoodCatalogViewSet, basename='foodcatalog')
router.register(r'muscles', MuscleViewSet, basename='muscle')
router.register(r'equipments', EquipmentViewSet, basename='equipment')
router.register(r'tags', TagViewSet, basename='tag')
router.register(r'sessions', WorkoutSessionViewSet, basename='workoutsession')
router.register(r'strength-sets', StrengthSetViewSet, basename='strengthset')
router.register(r'cardio-entries', CardioEntryViewSet, basename='cardioentry')
router.register(r'nutrition-logs', NutritionLogViewSet, basename='nutritionlog')
router.register(r'measurements', MeasurementViewSet, basename='measurement')
router.register(r'goals', GoalViewSet, basename='goal')

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # URL for user registration
    path('', include(router.urls)),
    path('register/', RegisterView.as_view(), name='auth_register'),
    path('weekly-plan/', WeeklyPlanView.as_view(), name='weekly_plan'),
    path('progress/summary/', ProgressStatsView.as_view(), name='progress_summary'),
    path('progress/exercise-trend/', ProgressExerciseTrendView.as_view(), name='progress_exercise_trend'),
]
