// Generated by Cursor AI for Maverick Aim Rush
// MAR/js/api.js - Helper functions for interacting with the backend API.

const API_BASE_URL = 'http://127.0.0.1:8000/api';

/**
 * Stores authentication tokens in localStorage.
 * @param {object} tokens - The tokens object with access and refresh properties.
 */
function storeTokens(tokens) {
    localStorage.setItem('accessToken', tokens.access);
    localStorage.setItem('refreshToken', tokens.refresh);
}

/**
 * Retrieves the access token from localStorage.
 * @returns {string|null} The access token.
 */
function getAccessToken() {
    return localStorage.getItem('accessToken');
}

/**
 * Retrieves the refresh token from localStorage.
 * @returns {string|null} The refresh token.
 */
function getRefreshToken() {
    return localStorage.getItem('refreshToken');
}

/**
 * Clears authentication tokens from localStorage.
 */
function clearTokens() {
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');
}

/**
 * Attempts to refresh the access token using the refresh token.
 * @returns {boolean} True if refresh was successful, false otherwise.
 */
async function refreshToken() {
    const refreshToken = getRefreshToken();
    if (!refreshToken) {
        return false;
    }

    try {
        const response = await fetch(`${API_BASE_URL}/auth/refresh/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ refresh: refreshToken }),
        });

        if (response.ok) {
            const newTokens = await response.json();
            storeTokens({ access: newTokens.access, refresh: refreshToken }); // Keep the old refresh token
            return true;
        } else {
            clearTokens(); // Refresh token is invalid, clear everything
            return false;
        }
    } catch (error) {
        console.error('Error refreshing token:', error);
        return false;
    }
}

/**
 * A wrapper for the fetch API that handles authentication and token refreshing.
 * @param {string} url - The URL to fetch.
 * @param {object} options - The options for the fetch request.
 * @returns {Promise<Response>} The fetch response.
 */
async function apiFetch(url, options = {}) {
    options.headers = options.headers || {};
    const accessToken = getAccessToken();
    const hadAuthHeader = Boolean(accessToken);
    if (hadAuthHeader) {
        options.headers['Authorization'] = `Bearer ${accessToken}`;
    }

    let response = await fetch(url, options);

    if (response.status === 401) {
        // Token might be expired. Try refresh first.
        const refreshed = await refreshToken();
        if (refreshed) {
            options.headers['Authorization'] = `Bearer ${getAccessToken()}`;
            response = await fetch(url, options);
        } else {
            // If refresh failed, clear tokens and retry ONCE without Authorization
            clearTokens();
            if (hadAuthHeader) {
                const headers = { ...(options.headers || {}) };
                delete headers['Authorization'];
                response = await fetch(url, { ...options, headers });
            }
        }
    }

    return response;
}

/**
 * Registers a new user.
 * @param {string} username
 * @param {string} password
 * @param {string} email
 * @returns {Promise<object>} The server response.
 */
async function register(username, password, email) {
    const response = await fetch(`${API_BASE_URL}/auth/register/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password, email }),
    });
    return response.json();
}


/**
 * Logs in a user and stores the tokens.
 * @param {string} username
 * @param {string} password
 * @returns {Promise<boolean>} True if login was successful.
 */
async function login(username, password) {
    try {
        const response = await fetch(`${API_BASE_URL}/auth/login/`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ username, password }),
        });

        if (response.ok) {
            const tokens = await response.json();
            storeTokens(tokens);
            return true;
        }
        return false;
    } catch (error) {
        console.error('Login failed:', error);
        return false;
    }
}

/**
 * Logs out the user by clearing tokens.
 */
function logout() {
    clearTokens();
    // window.location.href = '/login.html'; // Example redirect
}


// --- API Functions for the Tracker App ---

/**
 * Fetches all workout sessions for the logged-in user.
 * @returns {Promise<Array>} A list of workout sessions.
 */
async function fetchSessions() {
    const response = await apiFetch(`${API_BASE_URL}/sessions/`);
    if (!response.ok) throw new Error('Failed to fetch sessions');
    const data = await response.json();
    return Array.isArray(data) ? data : (data.results || []);
}

/**
 * Fetch exercises with optional filters.
 * @param {Object} params - e.g. { category: 'strength', recommended_for_goal: 'muscle_gain' }
 */
async function fetchExercises(params = {}) {
    const qs = new URLSearchParams(params).toString();
    const url = `${API_BASE_URL}/exercises/${qs ? `?${qs}` : ''}`;
    const response = await apiFetch(url);
    if (!response.ok) throw new Error('Failed to fetch exercises');
    const data = await response.json();
    // Return the full data object for pagination and facets
    return data;
}

/**
 * Creates a new workout session.
 * @param {string} date - The date of the session (e.g., 'YYYY-MM-DD').
 * @param {number} duration_minutes - The duration of the session in minutes.
 * @returns {Promise<object>} The created session object.
 */
async function createSession(date, duration_minutes) {
    const response = await apiFetch(`${API_BASE_URL}/sessions/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ date, duration_minutes }),
    });
    if (!response.ok) throw new Error('Failed to create session');
    return response.json();
}

/**
 * Updates an existing workout session (e.g., to set duration).
 * @param {number} session_id
 * @param {object} data - fields to update, e.g. { duration_minutes: 45 }
 */
async function updateSession(session_id, data) {
    const response = await apiFetch(`${API_BASE_URL}/sessions/${session_id}/`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
    });
    if (!response.ok) throw new Error('Failed to update session');
    return response.json();
}

/**
 * Creates a new strength set for a given session.
 * @param {number} session_id
 * @param {number} exercise_id
 * @param {number} set_number
 * @param {number} reps
 * @param {number} weight_kg
 * @returns {Promise<object>} The created strength set object.
 */
async function createStrengthSet(session_id, exercise_id, set_number, reps, weight_kg) {
    const response = await apiFetch(`${API_BASE_URL}/strength-sets/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
            session: session_id, 
            exercise: exercise_id, 
            set_number, 
            reps, 
            weight_kg 
        }),
    });
    if (!response.ok) throw new Error('Failed to create strength set');
    return response.json();
}

/**
 * Create a cardio entry for a session.
 */
async function createCardioEntry(session_id, exercise_id, duration_minutes, distance_km) {
    const response = await apiFetch(`${API_BASE_URL}/cardio-entries/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session: session_id, exercise: exercise_id, duration_minutes, distance_km }),
    });
    if (!response.ok) throw new Error('Failed to create cardio entry');
    return response.json();
}

/**
 * Fetches all nutrition logs for the logged-in user.
 * @returns {Promise<Array>} A list of nutrition logs.
 */
async function fetchNutritionLogs() {
    const response = await apiFetch(`${API_BASE_URL}/nutrition-logs/`);
    if (!response.ok) throw new Error('Failed to fetch nutrition logs');
    return response.json();
}

/**
 * Creates a new nutrition log entry.
 * @param {object} logData - The data for the nutrition log.
 * @returns {Promise<object>} The created nutrition log object.
 */
async function createNutritionLog(logData) {
    const response = await apiFetch(`${API_BASE_URL}/nutrition-logs/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(logData),
    });
    if (!response.ok) throw new Error('Failed to create nutrition log');
    return response.json();
}

// Expose helpers to window for robustness
window.getAccessToken = window.getAccessToken || getAccessToken;
window.login = window.login || login;
window.register = window.register || register;
window.logout = window.logout || logout;
window.fetchExercises = window.fetchExercises || fetchExercises;
window.fetchSessions = window.fetchSessions || fetchSessions;