# Generated by Cursor AI for Maverick Aim Rush
from django.core.management.base import BaseCommand
from tracker.models import ExerciseCatalog, FoodCatalog, Muscle, Equipment, ExerciseMuscle, Tag

class Command(BaseCommand):
    help = 'Seeds the database with a basic list of exercises.'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.SUCCESS('Seeding exercise data...'))
        
        exercises_to_add = [
            # Strength
            {'name': 'Barbell Bench Press', 'category': 'strength', 'equipment': 'Barbell, Bench', 'muscles': 'Chest, Triceps, Shoulders', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Dumbbell Bench Press', 'category': 'strength', 'equipment': 'Dumbbells, Bench', 'muscles': 'Chest, Triceps, Shoulders', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Back Squat', 'category': 'strength', 'equipment': 'Barbell, Squat Rack', 'muscles': 'Quads, Glutes, Hamstrings, Core', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Goblet Squat', 'category': 'strength', 'equipment': 'Dumbbell or Kettlebell', 'muscles': 'Quads, Glutes, Core', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Conventional Deadlift', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Back, Glutes, Hamstrings, Core', 'difficulty': 'advanced', 'goal': 'muscle_gain'},
            {'name': 'Romanian Deadlift', 'category': 'strength', 'equipment': 'Barbell or Dumbbells', 'muscles': 'Hamstrings, Glutes, Lower Back', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Standing Overhead Press', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Shoulders, Triceps, Core', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Barbell Row', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Back, Biceps', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Lat Pulldown', 'category': 'strength', 'equipment': 'Cable Machine', 'muscles': 'Back, Biceps', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Incline Barbell Bench Press', 'category': 'strength', 'equipment': 'Barbell, Bench', 'muscles': 'Chest, Shoulders, Triceps', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Incline Dumbbell Bench Press', 'category': 'strength', 'equipment': 'Dumbbells, Bench', 'muscles': 'Chest, Shoulders, Triceps', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Decline Bench Press', 'category': 'strength', 'equipment': 'Barbell, Bench', 'muscles': 'Chest, Triceps, Shoulders', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Dumbbell Fly', 'category': 'strength', 'equipment': 'Dumbbells, Bench', 'muscles': 'Chest, Shoulders', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Cable Fly', 'category': 'strength', 'equipment': 'Cable Machine', 'muscles': 'Chest, Shoulders', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Seated Cable Row', 'category': 'strength', 'equipment': 'Cable Machine', 'muscles': 'Back, Biceps', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'One-Arm Dumbbell Row', 'category': 'strength', 'equipment': 'Dumbbells, Bench', 'muscles': 'Back, Biceps', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Pendlay Row', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Back, Biceps', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'T-Bar Row', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Back, Biceps', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Face Pull', 'category': 'strength', 'equipment': 'Cable Machine', 'muscles': 'Shoulders, Back', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Lateral Raise', 'category': 'strength', 'equipment': 'Dumbbells', 'muscles': 'Shoulders', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Rear Delt Fly', 'category': 'strength', 'equipment': 'Dumbbells', 'muscles': 'Shoulders, Back', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Barbell Curl', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Biceps, Forearms', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Dumbbell Curl', 'category': 'strength', 'equipment': 'Dumbbells', 'muscles': 'Biceps, Forearms', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Hammer Curl', 'category': 'strength', 'equipment': 'Dumbbells', 'muscles': 'Biceps, Forearms', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Tricep Pushdown', 'category': 'strength', 'equipment': 'Cable Machine', 'muscles': 'Triceps', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Skull Crushers', 'category': 'strength', 'equipment': 'Barbell, Bench', 'muscles': 'Triceps', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Dips', 'category': 'strength', 'equipment': 'Dip Bars', 'muscles': 'Chest, Triceps, Shoulders', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Hip Thrust', 'category': 'strength', 'equipment': 'Barbell, Bench', 'muscles': 'Glutes, Hamstrings', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Leg Press', 'category': 'strength', 'equipment': 'Leg Press Machine', 'muscles': 'Quads, Glutes, Hamstrings', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Leg Extension', 'category': 'strength', 'equipment': 'Leg Extension Machine', 'muscles': 'Quads', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Leg Curl', 'category': 'strength', 'equipment': 'Leg Curl Machine', 'muscles': 'Hamstrings', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Seated Calf Raise', 'category': 'strength', 'equipment': 'Calf Raise Machine', 'muscles': 'Calves', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Standing Calf Raise', 'category': 'strength', 'equipment': 'Calf Raise Machine', 'muscles': 'Calves', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Bulgarian Split Squat', 'category': 'strength', 'equipment': 'Dumbbells, Bench', 'muscles': 'Quads, Glutes, Hamstrings', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Front Squat', 'category': 'strength', 'equipment': 'Barbell, Squat Rack', 'muscles': 'Quads, Core, Glutes', 'difficulty': 'advanced', 'goal': 'muscle_gain'},
            {'name': 'Sumo Deadlift', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Glutes, Hamstrings, Back', 'difficulty': 'advanced', 'goal': 'muscle_gain'},
            {'name': 'Trap Bar Deadlift', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Glutes, Quads, Back', 'difficulty': 'intermediate', 'goal': 'muscle_gain'},
            {'name': 'Good Morning', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Hamstrings, Lower Back, Glutes', 'difficulty': 'advanced', 'goal': 'muscle_gain'},
            {'name': 'Incline Dumbbell Row', 'category': 'strength', 'equipment': 'Dumbbells, Bench', 'muscles': 'Back, Biceps', 'difficulty': 'beginner', 'goal': 'muscle_gain'},
            {'name': 'Landmine Press', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Shoulders, Chest, Core', 'difficulty': 'intermediate', 'goal': 'performance'},
            {'name': 'Farmer Carry', 'category': 'strength', 'equipment': 'Dumbbells', 'muscles': 'Forearms, Traps, Core', 'difficulty': 'beginner', 'goal': 'performance'},
            {'name': 'Push Press', 'category': 'strength', 'equipment': 'Barbell', 'muscles': 'Shoulders, Triceps, Legs', 'difficulty': 'advanced', 'goal': 'performance'},

            # Bodyweight
            {'name': 'Pull-up', 'category': 'bodyweight', 'equipment': 'Pull-up Bar', 'muscles': 'Back, Biceps', 'difficulty': 'intermediate', 'goal': 'general_fitness'},
            {'name': 'Chin-up', 'category': 'bodyweight', 'equipment': 'Pull-up Bar', 'muscles': 'Biceps, Back', 'difficulty': 'intermediate', 'goal': 'general_fitness'},
            {'name': 'Push-up', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Chest, Triceps, Shoulders, Core', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Bodyweight Squat', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Quads, Glutes', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Plank', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Core', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Lunge', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Quads, Glutes', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Burpee', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Full Body, Cardiovascular', 'difficulty': 'intermediate', 'goal': 'weight_loss'},
            {'name': 'Mountain Climbers', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Core, Shoulders, Legs', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Hollow Hold', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Core', 'difficulty': 'intermediate', 'goal': 'general_fitness'},
            {'name': 'Hanging Leg Raise', 'category': 'bodyweight', 'equipment': 'Pull-up Bar', 'muscles': 'Core, Hip Flexors', 'difficulty': 'intermediate', 'goal': 'general_fitness'},
            {'name': 'Sit-up', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Core', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Crunch', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Core', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Bicycle Crunch', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Core, Obliques', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Russian Twist', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Core, Obliques', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Glute Bridge', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Glutes, Hamstrings', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Pistol Squat', 'category': 'bodyweight', 'equipment': 'Bodyweight', 'muscles': 'Quads, Glutes', 'difficulty': 'advanced', 'goal': 'performance'},
            
            # Cardio
            {'name': 'Running (Treadmill)', 'category': 'cardio', 'equipment': 'Treadmill', 'muscles': 'Legs, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Cycling (Stationary Bike)', 'category': 'cardio', 'equipment': 'Stationary Bike', 'muscles': 'Legs, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Rowing Machine', 'category': 'cardio', 'equipment': 'Rowing Machine', 'muscles': 'Full Body, Cardiovascular', 'difficulty': 'intermediate', 'goal': 'weight_loss'},
            {'name': 'Jumping Jacks', 'category': 'cardio', 'equipment': 'Bodyweight', 'muscles': 'Full Body, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Jump Rope', 'category': 'cardio', 'equipment': 'Jump Rope', 'muscles': 'Full Body, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Elliptical', 'category': 'cardio', 'equipment': 'Elliptical', 'muscles': 'Full Body, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Stair Climber', 'category': 'cardio', 'equipment': 'Stair Climber', 'muscles': 'Legs, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Assault Bike', 'category': 'cardio', 'equipment': 'Assault Bike', 'muscles': 'Full Body, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            {'name': 'Ski Erg', 'category': 'cardio', 'equipment': 'Ski Erg', 'muscles': 'Upper Body, Cardiovascular', 'difficulty': 'beginner', 'goal': 'weight_loss'},
            
            # Flexibility
            {'name': 'Hamstring Stretch', 'category': 'flexibility', 'equipment': 'Bodyweight', 'muscles': 'Hamstrings', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Quad Stretch', 'category': 'flexibility', 'equipment': 'Bodyweight', 'muscles': 'Quadriceps', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Yoga - Downward Dog', 'category': 'flexibility', 'equipment': 'Yoga Mat', 'muscles': 'Full Body', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Hip Flexor Stretch', 'category': 'flexibility', 'equipment': 'Bodyweight', 'muscles': 'Hip Flexors', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Calf Stretch', 'category': 'flexibility', 'equipment': 'Bodyweight', 'muscles': 'Calves', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Shoulder Dislocates', 'category': 'flexibility', 'equipment': 'PVC Pipe', 'muscles': 'Shoulders', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Thoracic Rotation', 'category': 'flexibility', 'equipment': 'Bodyweight', 'muscles': 'Back', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Pigeon Pose', 'category': 'flexibility', 'equipment': 'Yoga Mat', 'muscles': 'Glutes, Hips', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Child\'s Pose', 'category': 'flexibility', 'equipment': 'Yoga Mat', 'muscles': 'Back, Hips', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Cobra Stretch', 'category': 'flexibility', 'equipment': 'Yoga Mat', 'muscles': 'Lower Back, Abs', 'difficulty': 'beginner', 'goal': 'general_fitness'},
            {'name': 'Cat-Cow', 'category': 'flexibility', 'equipment': 'Yoga Mat', 'muscles': 'Spine, Back', 'difficulty': 'beginner', 'goal': 'general_fitness'},
        ]

        # Pre-create some muscles and equipments referenced above
        muscle_names = ['Chest', 'Triceps', 'Shoulders', 'Back', 'Biceps', 'Quads', 'Glutes', 'Hamstrings', 'Core', 'Quadriceps', 'Forearms', 'Calves', 'Traps', 'Lats', 'Lower Back', 'Abs', 'Obliques', 'Hip Flexors', 'Adductors', 'Abductors']
        name_to_muscle = {}
        for m in muscle_names:
            obj, _ = Muscle.objects.get_or_create(name=m)
            name_to_muscle[m] = obj

        equipment_names = ['Barbell', 'Bench', 'Dumbbells', 'Squat Rack', 'Kettlebell', 'Cable Machine', 'Pull-up Bar', 'Stationary Bike', 'Rowing Machine', 'Treadmill', 'Yoga Mat', 'Bodyweight', 'Dip Bars', 'Leg Press Machine', 'Leg Extension Machine', 'Leg Curl Machine', 'Calf Raise Machine', 'Jump Rope', 'Elliptical', 'Stair Climber', 'Assault Bike', 'Ski Erg', 'PVC Pipe', 'Smith Machine', 'Hack Squat Machine', 'Seated Row Machine', 'Pec Deck', 'Machine']
        name_to_equipment = {}
        for e in equipment_names:
            obj, _ = Equipment.objects.get_or_create(name=e)
            name_to_equipment[e] = obj

        for exercise_data in exercises_to_add:
            exercise, _ = ExerciseCatalog.objects.get_or_create(
                name=exercise_data['name'],
                defaults={
                    'category': exercise_data['category'],
                    'equipment_needed': exercise_data.get('equipment'),
                    'target_muscle_groups': exercise_data.get('muscles'),
                    'difficulty_level': exercise_data.get('difficulty'),
                    'recommended_for_goal': exercise_data.get('goal'),
                }
            )

            # Link equipments
            equipment_field = exercise_data.get('equipment', '')
            for token in [t.strip() for t in equipment_field.split(',') if t.strip()]:
                eq = name_to_equipment.get(token)
                if eq:
                    exercise.equipments.add(eq)

            # Link primary/secondary muscles via heuristic from text
            muscles_text = (exercise_data.get('muscles') or '')
            # naive split by comma and map first as primary
            parts = [p.strip() for p in muscles_text.replace('Quadriceps', 'Quads').split(',') if p.strip()]
            for i, part in enumerate(parts):
                # Map plurals to canonical muscle names
                canonical = part
                if canonical == 'Quadriceps':
                    canonical = 'Quads'
                m = name_to_muscle.get(canonical) or name_to_muscle.get(canonical.rstrip('s'))
                if m:
                    ExerciseMuscle.objects.get_or_create(exercise=exercise, muscle=m, role='primary' if i == 0 else 'secondary')

        # Programmatically generate many more exercises from templates
        templates = [
            # movement, muscles, equipments, category
            ('Chest Press', 'Chest, Triceps, Shoulders', ['Barbell', 'Dumbbells', 'Smith Machine', 'Chest Press Machine', 'Machine'], 'strength'),
            ('Chest Fly', 'Chest, Shoulders', ['Dumbbells', 'Cable Machine', 'Pec Deck'], 'strength'),
            ('Row', 'Back, Biceps', ['Barbell', 'Dumbbells', 'Seated Row Machine', 'Cable Machine'], 'strength'),
            ('Pulldown', 'Back, Biceps, Lats', ['Cable Machine'], 'strength'),
            ('Pullover', 'Back, Lats, Chest', ['Dumbbells', 'Cable Machine'], 'strength'),
            ('Lateral Raise', 'Shoulders', ['Dumbbells', 'Cable Machine'], 'strength'),
            ('Front Raise', 'Shoulders', ['Dumbbells', 'Cable Machine'], 'strength'),
            ('Rear Delt Fly', 'Shoulders, Back', ['Dumbbells', 'Cable Machine'], 'strength'),
            ('Curl', 'Biceps, Forearms', ['Barbell', 'Dumbbells', 'Cable Machine'], 'strength'),
            ('Hammer Curl', 'Biceps, Forearms', ['Dumbbells'], 'strength'),
            ('Tricep Extension', 'Triceps', ['Dumbbells', 'Cable Machine'], 'strength'),
            ('Pushdown', 'Triceps', ['Cable Machine'], 'strength'),
            ('Hip Thrust', 'Glutes, Hamstrings', ['Barbell', 'Smith Machine'], 'strength'),
            ('Split Squat', 'Quads, Glutes', ['Dumbbells', 'Barbell'], 'strength'),
            ('Step-up', 'Quads, Glutes', ['Dumbbells', 'Barbell'], 'strength'),
            ('Leg Press', 'Quads, Glutes, Hamstrings', ['Leg Press Machine'], 'strength'),
            ('Leg Extension', 'Quads', ['Leg Extension Machine'], 'strength'),
            ('Leg Curl', 'Hamstrings', ['Leg Curl Machine'], 'strength'),
            ('Calf Raise', 'Calves', ['Calf Raise Machine', 'Smith Machine'], 'strength'),
            ('Good Morning', 'Hamstrings, Lower Back', ['Barbell'], 'strength'),
            ('Overhead Press', 'Shoulders, Triceps, Core', ['Barbell', 'Dumbbells'], 'strength'),
            ('Kettlebell Swing', 'Glutes, Hamstrings, Back', ['Kettlebell'], 'strength'),
            ('Farmer Carry', 'Forearms, Traps, Core', ['Dumbbells'], 'strength'),
            ('Hack Squat', 'Quads, Glutes', ['Hack Squat Machine'], 'strength'),
            ('Smith Squat', 'Quads, Glutes', ['Smith Machine'], 'strength'),
            ('Incline Press', 'Chest, Shoulders, Triceps', ['Barbell', 'Dumbbells', 'Smith Machine'], 'strength'),
            ('Decline Press', 'Chest, Triceps, Shoulders', ['Barbell', 'Dumbbells', 'Smith Machine'], 'strength'),
            # cardio
            ('Run', 'Legs, Cardiovascular', ['Treadmill'], 'cardio'),
            ('Bike', 'Legs, Cardiovascular', ['Stationary Bike', 'Assault Bike'], 'cardio'),
            ('Row', 'Full Body, Cardiovascular', ['Rowing Machine'], 'cardio'),
            ('Elliptical', 'Full Body, Cardiovascular', ['Elliptical'], 'cardio'),
            ('Stair Climb', 'Legs, Cardiovascular', ['Stair Climber'], 'cardio'),
            ('Ski Erg', 'Upper Body, Cardiovascular', ['Ski Erg'], 'cardio'),
            ('Jump Rope', 'Full Body, Cardiovascular', ['Jump Rope'], 'cardio'),
            # core
            ('Crunch', 'Abs', ['Bodyweight'], 'bodyweight'),
            ('Hanging Leg Raise', 'Abs, Hip Flexors', ['Pull-up Bar'], 'bodyweight'),
            ('Plank', 'Core', ['Bodyweight'], 'bodyweight'),
            ('Side Plank', 'Core, Obliques', ['Bodyweight'], 'bodyweight'),
            ('Russian Twist', 'Core, Obliques', ['Bodyweight'], 'bodyweight'),
        ]

        generated = []
        for movement, muscles, eqs, category in templates:
            for eq in eqs:
                name = f"{eq} {movement}" if eq not in ['Bodyweight'] else movement
                generated.append({'name': name, 'category': category, 'equipment': eq, 'muscles': muscles, 'difficulty': 'beginner', 'goal': 'general_fitness'})

        # Limit total size to avoid runaway generation; target ~160+ total
        added_count = 0
        for g in generated:
            if added_count > 200:
                break
            exercise, created = ExerciseCatalog.objects.get_or_create(
                name=g['name'],
                defaults={
                    'category': g['category'],
                    'equipment_needed': g.get('equipment'),
                    'target_muscle_groups': g.get('muscles'),
                    'difficulty_level': g.get('difficulty'),
                    'recommended_for_goal': g.get('goal'),
                }
            )
            if created:
                added_count += 1
            # Link equipment
            eq = name_to_equipment.get(g['equipment'])
            if eq:
                exercise.equipments.add(eq)
            # Link muscles (primary first token)
            parts = [p.strip() for p in g['muscles'].split(',') if p.strip()]
            for i, part in enumerate(parts):
                canon = part
                m = name_to_muscle.get(canon) or name_to_muscle.get(canon.rstrip('s'))
                if m:
                    ExerciseMuscle.objects.get_or_create(exercise=exercise, muscle=m, role='primary' if i == 0 else 'secondary')

        # Tag examples
        for tag_name in ['compound', 'isolation', 'push', 'pull', 'hinge', 'squat', 'carry']:
            Tag.objects.get_or_create(name=tag_name)
        
        # Seed a comprehensive food catalog with per-100g nutrition
        foods_to_add = [
            # Proteins
            {'name': 'Chicken Breast (cooked, skinless)', 'cal': 165, 'p': 31, 'c': 0, 'f': 3.6},
            {'name': 'Chicken Breast', 'cal': 165, 'p': 31, 'c': 0, 'f': 3.6},
            {'name': 'Salmon (cooked)', 'cal': 206, 'p': 22, 'c': 0, 'f': 12},
            {'name': 'Tuna (canned in water)', 'cal': 116, 'p': 26, 'c': 0, 'f': 0.8},
            {'name': 'Egg (whole, boiled)', 'cal': 155, 'p': 13, 'c': 1.1, 'f': 11},
            {'name': 'Egg', 'cal': 155, 'p': 13, 'c': 1.1, 'f': 11},
            {'name': 'Lean Beef (cooked)', 'cal': 250, 'p': 26, 'c': 0, 'f': 15},
            {'name': 'Turkey Breast (cooked)', 'cal': 135, 'p': 30, 'c': 0, 'f': 1},
            {'name': 'Tofu', 'cal': 76, 'p': 8, 'c': 1.9, 'f': 4.8},
            {'name': 'Greek Yogurt (nonfat)', 'cal': 59, 'p': 10, 'c': 3.6, 'f': 0.4},
            {'name': 'Greek Yogurt', 'cal': 59, 'p': 10, 'c': 3.6, 'f': 0.4},
            {'name': 'Cottage Cheese (low fat)', 'cal': 98, 'p': 11, 'c': 3.4, 'f': 4.3},
            
            # Grains & Carbs
            {'name': 'White Rice (cooked)', 'cal': 130, 'p': 2.4, 'c': 28, 'f': 0.3},
            {'name': 'White Rice', 'cal': 130, 'p': 2.4, 'c': 28, 'f': 0.3},
            {'name': 'Brown Rice (cooked)', 'cal': 123, 'p': 2.6, 'c': 25.6, 'f': 1},
            {'name': 'Brown Rice', 'cal': 123, 'p': 2.6, 'c': 25.6, 'f': 1},
            {'name': 'Quinoa (cooked)', 'cal': 120, 'p': 4.4, 'c': 22, 'f': 1.9},
            {'name': 'Quinoa', 'cal': 120, 'p': 4.4, 'c': 22, 'f': 1.9},
            {'name': 'Oats (dry)', 'cal': 389, 'p': 16.9, 'c': 66.3, 'f': 6.9},
            {'name': 'Oats', 'cal': 389, 'p': 16.9, 'c': 66.3, 'f': 6.9},
            {'name': 'Whole Wheat Bread', 'cal': 247, 'p': 13, 'c': 41, 'f': 4.2},
            {'name': 'Pasta (cooked)', 'cal': 131, 'p': 5, 'c': 25, 'f': 1.1},
            {'name': 'Sweet Potato (baked)', 'cal': 86, 'p': 1.6, 'c': 20, 'f': 0.1},
            {'name': 'Sweet Potato', 'cal': 86, 'p': 1.6, 'c': 20, 'f': 0.1},
            
            # Fruits
            {'name': 'Banana', 'cal': 89, 'p': 1.1, 'c': 22.8, 'f': 0.3},
            {'name': 'Apple', 'cal': 52, 'p': 0.3, 'c': 13.8, 'f': 0.2},
            {'name': 'Orange', 'cal': 47, 'p': 0.9, 'c': 11.8, 'f': 0.1},
            {'name': 'Pineapple', 'cal': 50, 'p': 0.5, 'c': 13.1, 'f': 0.1},
            {'name': 'Strawberries', 'cal': 32, 'p': 0.7, 'c': 7.7, 'f': 0.3},
            {'name': 'Blueberries', 'cal': 57, 'p': 0.7, 'c': 14.5, 'f': 0.3},
            {'name': 'Grapes', 'cal': 62, 'p': 0.6, 'c': 16.3, 'f': 0.2},
            {'name': 'Mango', 'cal': 60, 'p': 0.8, 'c': 15, 'f': 0.4},
            {'name': 'Avocado', 'cal': 160, 'p': 2, 'c': 8.5, 'f': 14.7},
            
            # Vegetables
            {'name': 'Broccoli', 'cal': 34, 'p': 2.8, 'c': 7, 'f': 0.4},
            {'name': 'Spinach', 'cal': 23, 'p': 2.9, 'c': 3.6, 'f': 0.4},
            {'name': 'Carrots', 'cal': 41, 'p': 0.9, 'c': 9.6, 'f': 0.2},
            {'name': 'Bell Peppers', 'cal': 31, 'p': 1, 'c': 7, 'f': 0.3},
            {'name': 'Tomatoes', 'cal': 18, 'p': 0.9, 'c': 3.9, 'f': 0.2},
            {'name': 'Cucumber', 'cal': 16, 'p': 0.7, 'c': 4, 'f': 0.1},
            {'name': 'Lettuce', 'cal': 15, 'p': 1.4, 'c': 2.9, 'f': 0.2},
            
            # Nuts & Seeds
            {'name': 'Almonds', 'cal': 579, 'p': 21.2, 'c': 21.7, 'f': 49.9},
            {'name': 'Walnuts', 'cal': 654, 'p': 15.2, 'c': 13.7, 'f': 65.2},
            {'name': 'Cashews', 'cal': 553, 'p': 18.2, 'c': 30.2, 'f': 43.9},
            {'name': 'Peanuts', 'cal': 567, 'p': 25.8, 'c': 16.1, 'f': 49.2},
            {'name': 'Peanut Butter', 'cal': 588, 'p': 25, 'c': 20, 'f': 50},
            {'name': 'Chia Seeds', 'cal': 486, 'p': 17, 'c': 42, 'f': 31},
            
            # Dairy & Alternatives
            {'name': 'Milk (whole)', 'cal': 61, 'p': 3.2, 'c': 4.8, 'f': 3.3},
            {'name': 'Milk (skim)', 'cal': 34, 'p': 3.4, 'c': 5, 'f': 0.1},
            {'name': 'Cheddar Cheese', 'cal': 402, 'p': 25, 'c': 1.3, 'f': 33},
            
            # Oils & Fats
            {'name': 'Olive Oil', 'cal': 884, 'p': 0, 'c': 0, 'f': 100},
            {'name': 'Coconut Oil', 'cal': 862, 'p': 0, 'c': 0, 'f': 100},
            {'name': 'Butter', 'cal': 717, 'p': 0.9, 'c': 0.1, 'f': 81},
            
            # Legumes
            {'name': 'Black Beans (cooked)', 'cal': 132, 'p': 8.9, 'c': 23, 'f': 0.5},
            {'name': 'Chickpeas (cooked)', 'cal': 164, 'p': 8.9, 'c': 27, 'f': 2.6},
            {'name': 'Lentils (cooked)', 'cal': 116, 'p': 9, 'c': 20, 'f': 0.4},
        ]

        for f in foods_to_add:
            FoodCatalog.objects.get_or_create(
                name=f['name'],
                defaults={
                    'calories_per_100g': f['cal'],
                    'protein_g_per_100g': f['p'],
                    'carbs_g_per_100g': f['c'],
                    'fat_g_per_100g': f['f'],
                }
            )

        self.stdout.write(self.style.SUCCESS('Finished seeding exercises, muscles, equipments, tags, and foods.'))
