# Generated by Django 5.2.5 on 2025-09-08 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_system', models.CharField(choices=[('imperial', 'Imperial (lb/mi)'), ('metric', 'Metric (kg/km)')], default='imperial', max_length=10)),
                ('distance_unit', models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], default='mi', max_length=2)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('primary_goal', models.CharField(blank=True, choices=[('cut', 'Cut (Fat Loss)'), ('recomp', 'Recomposition'), ('muscle_gain', 'Muscle Gain'), ('performance', 'Performance')], max_length=20, null=True)),
                ('days_per_week', models.IntegerField(default=3)),
                ('equipment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
